name:                getprogrammingwithhaskell
version:             0.1.0.0
github:              "jjunqueira/getprogrammingwithhaskell"
license:             BSD3
author:              "Joshua Junqueira"
maintainer:          "joshua.junqueira@gmail.com"
copyright:           "2018 Joshua Junqueira"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/getprogrammingwithhaskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- random
- split
- text
- bytestring

library:
  source-dirs: src

executables:
  getprogrammingwithhaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - getprogrammingwithhaskell

tests:
  getprogrammingwithhaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - getprogrammingwithhaskell
